[package]
name = "wired-rs"
version = "0.1.2"
authors = ["iostapyshyn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.2"
imageproc = "0.19.2"

[dependencies.sdl2]
version = "0.33.0"
default-features = false
features = ["unsafe_textures"]